package com.example.tnn.greendaotest.dao;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT. Enable "keep" sections if you want to edit. 
/**
 * Entity mapped to table "CARD_INFO".
 */
public class CardInfo {

    private Long id;
    /** Not-null value. */
    private String card;
    private Integer num;

    public CardInfo() {
    }

    public CardInfo(Long id) {
        this.id = id;
    }

    public CardInfo(Long id, String card, Integer num) {
        this.id = id;
        this.card = card;
        this.num = num;
    }

    public Long getId() {
        return id;
    }

    public void setId(Long id) {
        this.id = id;
    }

    /** Not-null value. */
    public String getCard() {
        return card;
    }

    /** Not-null value; ensure this value is available before it is saved to the database. */
    public void setCard(String card) {
        this.card = card;
    }

    public Integer getNum() {
        return num;
    }

    public void setNum(Integer num) {
        this.num = num;
    }

}
