package com.example.tnn.greendaotest.dao;

import android.database.sqlite.SQLiteDatabase;

import java.util.Map;

import de.greenrobot.dao.AbstractDao;
import de.greenrobot.dao.AbstractDaoSession;
import de.greenrobot.dao.identityscope.IdentityScopeType;
import de.greenrobot.dao.internal.DaoConfig;

import com.example.tnn.greendaotest.dao.UserInfo;
import com.example.tnn.greendaotest.dao.CardInfo;

import com.example.tnn.greendaotest.dao.UserInfoDao;
import com.example.tnn.greendaotest.dao.CardInfoDao;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT.

/**
 * {@inheritDoc}
 * 
 * @see de.greenrobot.dao.AbstractDaoSession
 */
public class DaoSession extends AbstractDaoSession {

    private final DaoConfig userInfoDaoConfig;
    private final DaoConfig cardInfoDaoConfig;

    private final UserInfoDao userInfoDao;
    private final CardInfoDao cardInfoDao;

    public DaoSession(SQLiteDatabase db, IdentityScopeType type, Map<Class<? extends AbstractDao<?, ?>>, DaoConfig>
            daoConfigMap) {
        super(db);

        userInfoDaoConfig = daoConfigMap.get(UserInfoDao.class).clone();
        userInfoDaoConfig.initIdentityScope(type);

        cardInfoDaoConfig = daoConfigMap.get(CardInfoDao.class).clone();
        cardInfoDaoConfig.initIdentityScope(type);

        userInfoDao = new UserInfoDao(userInfoDaoConfig, this);
        cardInfoDao = new CardInfoDao(cardInfoDaoConfig, this);

        registerDao(UserInfo.class, userInfoDao);
        registerDao(CardInfo.class, cardInfoDao);
    }
    
    public void clear() {
        userInfoDaoConfig.getIdentityScope().clear();
        cardInfoDaoConfig.getIdentityScope().clear();
    }

    public UserInfoDao getUserInfoDao() {
        return userInfoDao;
    }

    public CardInfoDao getCardInfoDao() {
        return cardInfoDao;
    }

}
